/* Generated by re2c 2.0.3 on Wed Dec  2 02:49:29 2020 */
// re2c -i -r --input-encoding utf8 -o reusable_block.c reusable_block.re.c
#include <assert.h>
#include <stdint.h>



static int lex_utf8(const uint8_t *YYCURSOR)
{
    const uint8_t *YYMARKER;
    
{
	uint8_t yych;
	yych = *YYCURSOR;
	switch (yych) {
	case 0xE2:	goto yy4;
	default:	goto yy2;
	}
yy2:
	++YYCURSOR;
yy3:
	{ return 1; }
yy4:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 0x88:	goto yy5;
	default:	goto yy3;
	}
yy5:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x80:	goto yy7;
	default:	goto yy6;
	}
yy6:
	YYCURSOR = YYMARKER;
	goto yy3;
yy7:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'x':	goto yy8;
	default:	goto yy6;
	}
yy8:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy9;
	default:	goto yy6;
	}
yy9:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0xE2:	goto yy10;
	default:	goto yy6;
	}
yy10:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x88:	goto yy11;
	default:	goto yy6;
	}
yy11:
	yych = *++YYCURSOR;
	switch (yych) {
	case 0x83:	goto yy12;
	default:	goto yy6;
	}
yy12:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'y':	goto yy13;
	default:	goto yy6;
	}
yy13:
	yych = *++YYCURSOR;
	switch (yych) {
	case ':':	goto yy14;
	default:	goto yy6;
	}
yy14:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy15;
	default:	goto yy6;
	}
yy15:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy16;
	default:	goto yy6;
	}
yy16:
	yych = *++YYCURSOR;
	switch (yych) {
	case '(':	goto yy17;
	default:	goto yy6;
	}
yy17:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'x':	goto yy18;
	default:	goto yy6;
	}
yy18:
	yych = *++YYCURSOR;
	switch (yych) {
	case ',':	goto yy19;
	default:	goto yy6;
	}
yy19:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy20;
	default:	goto yy6;
	}
yy20:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'y':	goto yy21;
	default:	goto yy6;
	}
yy21:
	yych = *++YYCURSOR;
	switch (yych) {
	case ')':	goto yy22;
	default:	goto yy6;
	}
yy22:
	++YYCURSOR;
	{ return 0; }
}

}

static int lex_utf32(const uint32_t *YYCURSOR)
{
    const uint32_t *YYMARKER;
    
{
	uint32_t yych;
	yych = *YYCURSOR;
	if (yych == 0x00002200) goto yy28;
	++YYCURSOR;
yy27:
	{ return 1; }
yy28:
	yych = *(YYMARKER = ++YYCURSOR);
	if (yych != 'x') goto yy27;
	yych = *++YYCURSOR;
	if (yych == ' ') goto yy31;
yy30:
	YYCURSOR = YYMARKER;
	goto yy27;
yy31:
	yych = *++YYCURSOR;
	if (yych != 0x00002203) goto yy30;
	yych = *++YYCURSOR;
	if (yych != 'y') goto yy30;
	yych = *++YYCURSOR;
	if (yych != ':') goto yy30;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy30;
	yych = *++YYCURSOR;
	if (yych != 'p') goto yy30;
	yych = *++YYCURSOR;
	if (yych != '(') goto yy30;
	yych = *++YYCURSOR;
	if (yych != 'x') goto yy30;
	yych = *++YYCURSOR;
	if (yych != ',') goto yy30;
	yych = *++YYCURSOR;
	if (yych != ' ') goto yy30;
	yych = *++YYCURSOR;
	if (yych != 'y') goto yy30;
	yych = *++YYCURSOR;
	if (yych != ')') goto yy30;
	++YYCURSOR;
	{ return 0; }
}

}

int main()
{
    static const uint8_t s8[] = // UTF-8
        { 0xe2, 0x88, 0x80, 0x78, 0x20, 0xe2, 0x88, 0x83, 0x79
        , 0x3a, 0x20, 0x70, 0x28, 0x78, 0x2c, 0x20, 0x79, 0x29 };

    static const uint32_t s32[] = // UTF32
        { 0x00002200, 0x00000078, 0x00000020, 0x00002203
        , 0x00000079, 0x0000003a, 0x00000020, 0x00000070
        , 0x00000028, 0x00000078, 0x0000002c, 0x00000020
        , 0x00000079, 0x00000029 };

    assert(lex_utf8(s8) == 0);
    assert(lex_utf32(s32) == 0);
    return 0;
}
