/* Generated by re2c 2.0.3 on Fri Nov 13 18:30:58 2020 */
#include <assert.h>

static int lex(const char *YYCURSOR)
{
	int count = 0;
loop:
	
{
	char yych;
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy2; // センチネル文字
	case ' ':	goto yy6; // 区切り文字
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy9; // [a-z]+ { ++count; goto loop; } の継続
	default:	goto yy4; // [a-z]+ { ++count; goto loop; } の失敗
	}
yy2: // [\x00] { return count; }
	++YYCURSOR;
	{ return count; }
yy4: // *      { return -1; }
	++YYCURSOR;
	{ return -1; }
yy6: // [ ]+   { goto loop; }
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy6;
	default:	goto yy8;
	}
yy8:
	{ goto loop; }
yy9:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy9;
	default:	goto yy11;
	}
yy11: // [a-z]+ { ++count; goto loop; } の成功
	{ ++count; goto loop; }
}

}

int main()
{
	assert(lex("") == 0);
	assert(lex("one two three") == 3);
	assert(lex("f0ur") == -1);
	return 0;
}
