/* Generated by re2c 2.0.3 on Mon Nov 16 03:15:09 2020 */
#include <assert.h>

static int lex(const char *YYCURSOR)
{
	int count = 0;
loop:
	
{
	char yych;
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy2;
	case ' ':	goto yy6;
	case '\'':	goto yy9;
	default:	goto yy4;
	}
yy2:
	++YYCURSOR;
	{ return count; }
yy4:
	++YYCURSOR;
	{ return -1; }
yy6:
	yych = *++YYCURSOR;
	switch (yych) {
	case ' ':	goto yy6;
	default:	goto yy8;
	}
yy8:
	{ goto loop; }
yy9:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\'':	goto yy11;
	case '\\':	goto yy13;
	default:	goto yy9;
	}
yy11:
	++YYCURSOR;
	{ ++count; goto loop; }
yy13:
	yych = *++YYCURSOR;
	goto yy9;
}

}

int main()
{
	assert(lex("") == 0);
	assert(lex("'one' 'two' 'three'") == 3);
	assert(lex("'f0ur'") == 1);
	assert(lex("'qu\0tes' 'are' 'fine: \\'' ") == 3);
	return 0;
}
